### ISSUE TITLE
Installation problem - clog or npm-clog

### ISSUE THREAD

**Issue by emcniece** [kentcdodds/clog-cli#6]
The README here and at the [npm repo](https://www.npmjs.com/package/npm-clog) says installation should be done like this:

```
npm install -g clog
```

[clog](https://www.npmjs.com/package/clog) is a different NPM package. Shouldn't it be more like this?

```
npm install -g npm-clog
```

**Comment by kentcdodds** [comment]
I need to give you an apology. For some reason, I want watching this repository so I want getting notifications about issues and pull requests. I am so incredibly sorry. Please forgive me. I really feel awful. I hope my unresponsiveness doesn't hinder you contributing more in the future.

As for your specific issue, I'll give it a closer look soon.

**Comment by kentcdodds** [comment]
I think this has been fixed. Sorry again!
